# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assessment.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'assessment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ssessment.proto\x12\x13zeyro.assessment.v1\"\x93\x01\n\x11\x41ssessmentRequest\x12\x15\n\rassessment_id\x18\x01 \x01(\t\x12\x12\n\npartner_id\x18\x02 \x01(\t\x12\x15\n\ruser_ref_hash\x18\x03 \x01(\t\x12\x10\n\x08products\x18\x04 \x03(\t\x12\x12\n\nconsent_id\x18\x05 \x01(\t\x12\x16\n\x0epartner_ref_id\x18\x06 \x01(\t\"0\n\x17\x41ssessmentStatusRequest\x12\x15\n\rassessment_id\x18\x01 \x01(\t\"p\n\x18\x41ssessmentStatusResponse\x12\x15\n\rassessment_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x16\n\x0eoverall_signal\x18\x03 \x01(\t\x12\x15\n\rscore_version\x18\x04 \x01(\t2\xf2\x01\n\x11\x41ssessmentService\x12i\n\x10\x43reateAssessment\x12&.zeyro.assessment.v1.AssessmentRequest\x1a-.zeyro.assessment.v1.AssessmentStatusResponse\x12r\n\x13GetAssessmentStatus\x12,.zeyro.assessment.v1.AssessmentStatusRequest\x1a-.zeyro.assessment.v1.AssessmentStatusResponseB?Z=github.com/arthazeyro/zeyro-b2b/proto/assessment;assessmentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assessment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/arthazeyro/zeyro-b2b/proto/assessment;assessmentpb'
  _globals['_ASSESSMENTREQUEST']._serialized_start=42
  _globals['_ASSESSMENTREQUEST']._serialized_end=189
  _globals['_ASSESSMENTSTATUSREQUEST']._serialized_start=191
  _globals['_ASSESSMENTSTATUSREQUEST']._serialized_end=239
  _globals['_ASSESSMENTSTATUSRESPONSE']._serialized_start=241
  _globals['_ASSESSMENTSTATUSRESPONSE']._serialized_end=353
  _globals['_ASSESSMENTSERVICE']._serialized_start=356
  _globals['_ASSESSMENTSERVICE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
