# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import assessment_pb2 as assessment__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in assessment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssessmentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAssessment = channel.unary_unary(
                '/zeyro.assessment.v1.AssessmentService/CreateAssessment',
                request_serializer=assessment__pb2.AssessmentRequest.SerializeToString,
                response_deserializer=assessment__pb2.AssessmentStatusResponse.FromString,
                _registered_method=True)
        self.GetAssessmentStatus = channel.unary_unary(
                '/zeyro.assessment.v1.AssessmentService/GetAssessmentStatus',
                request_serializer=assessment__pb2.AssessmentStatusRequest.SerializeToString,
                response_deserializer=assessment__pb2.AssessmentStatusResponse.FromString,
                _registered_method=True)


class AssessmentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateAssessment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssessmentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssessmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAssessment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAssessment,
                    request_deserializer=assessment__pb2.AssessmentRequest.FromString,
                    response_serializer=assessment__pb2.AssessmentStatusResponse.SerializeToString,
            ),
            'GetAssessmentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssessmentStatus,
                    request_deserializer=assessment__pb2.AssessmentStatusRequest.FromString,
                    response_serializer=assessment__pb2.AssessmentStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zeyro.assessment.v1.AssessmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zeyro.assessment.v1.AssessmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssessmentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAssessment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeyro.assessment.v1.AssessmentService/CreateAssessment',
            assessment__pb2.AssessmentRequest.SerializeToString,
            assessment__pb2.AssessmentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssessmentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeyro.assessment.v1.AssessmentService/GetAssessmentStatus',
            assessment__pb2.AssessmentStatusRequest.SerializeToString,
            assessment__pb2.AssessmentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
