# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audit.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udit.proto\x12\x0ezeyro.audit.v1\"\xb5\x01\n\x11\x41uditEventRequest\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x12\n\npartner_id\x18\x02 \x01(\t\x12\x12\n\nactor_type\x18\x03 \x01(\t\x12\x11\n\tactor_ref\x18\x04 \x01(\t\x12\x15\n\rresource_type\x18\x05 \x01(\t\x12\x14\n\x0cresource_ref\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x14\n\x0cpayload_json\x18\x08 \x01(\t\";\n\x12\x41uditEventResponse\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x13\n\x0boccurred_at\x18\x02 \x01(\t2h\n\x0c\x41uditService\x12X\n\x0fWriteAuditEvent\x12!.zeyro.audit.v1.AuditEventRequest\x1a\".zeyro.audit.v1.AuditEventResponseB5Z3github.com/arthazeyro/zeyro-b2b/proto/audit;auditpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/arthazeyro/zeyro-b2b/proto/audit;auditpb'
  _globals['_AUDITEVENTREQUEST']._serialized_start=32
  _globals['_AUDITEVENTREQUEST']._serialized_end=213
  _globals['_AUDITEVENTRESPONSE']._serialized_start=215
  _globals['_AUDITEVENTRESPONSE']._serialized_end=274
  _globals['_AUDITSERVICE']._serialized_start=276
  _globals['_AUDITSERVICE']._serialized_end=380
# @@protoc_insertion_point(module_scope)
