# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import consent_pb2 as consent__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in consent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateConsent = channel.unary_unary(
                '/zeyro.consent.v1.ConsentService/InitiateConsent',
                request_serializer=consent__pb2.ConsentInitiateRequest.SerializeToString,
                response_deserializer=consent__pb2.ConsentResponse.FromString,
                _registered_method=True)
        self.GetConsentStatus = channel.unary_unary(
                '/zeyro.consent.v1.ConsentService/GetConsentStatus',
                request_serializer=consent__pb2.ConsentStatusRequest.SerializeToString,
                response_deserializer=consent__pb2.ConsentResponse.FromString,
                _registered_method=True)


class ConsentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def InitiateConsent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateConsent': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateConsent,
                    request_deserializer=consent__pb2.ConsentInitiateRequest.FromString,
                    response_serializer=consent__pb2.ConsentResponse.SerializeToString,
            ),
            'GetConsentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsentStatus,
                    request_deserializer=consent__pb2.ConsentStatusRequest.FromString,
                    response_serializer=consent__pb2.ConsentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zeyro.consent.v1.ConsentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zeyro.consent.v1.ConsentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitiateConsent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeyro.consent.v1.ConsentService/InitiateConsent',
            consent__pb2.ConsentInitiateRequest.SerializeToString,
            consent__pb2.ConsentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeyro.consent.v1.ConsentService/GetConsentStatus',
            consent__pb2.ConsentStatusRequest.SerializeToString,
            consent__pb2.ConsentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
