# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: consent.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'consent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rconsent.proto\x12\x10zeyro.consent.v1\"}\n\x16\x43onsentInitiateRequest\x12\x12\n\npartner_id\x18\x01 \x01(\t\x12\x15\n\ruser_ref_hash\x18\x02 \x01(\t\x12\x14\n\x0cpurpose_code\x18\x03 \x01(\t\x12\x11\n\tdata_from\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x61ta_to\x18\x05 \x01(\t\"I\n\x0f\x43onsentResponse\x12\x12\n\nconsent_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\t\"*\n\x14\x43onsentStatusRequest\x12\x12\n\nconsent_id\x18\x01 \x01(\t2\xcf\x01\n\x0e\x43onsentService\x12^\n\x0fInitiateConsent\x12(.zeyro.consent.v1.ConsentInitiateRequest\x1a!.zeyro.consent.v1.ConsentResponse\x12]\n\x10GetConsentStatus\x12&.zeyro.consent.v1.ConsentStatusRequest\x1a!.zeyro.consent.v1.ConsentResponseB9Z7github.com/arthazeyro/zeyro-b2b/proto/consent;consentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/arthazeyro/zeyro-b2b/proto/consent;consentpb'
  _globals['_CONSENTINITIATEREQUEST']._serialized_start=35
  _globals['_CONSENTINITIATEREQUEST']._serialized_end=160
  _globals['_CONSENTRESPONSE']._serialized_start=162
  _globals['_CONSENTRESPONSE']._serialized_end=235
  _globals['_CONSENTSTATUSREQUEST']._serialized_start=237
  _globals['_CONSENTSTATUSREQUEST']._serialized_end=279
  _globals['_CONSENTSERVICE']._serialized_start=282
  _globals['_CONSENTSERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
