# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: features.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'features.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x65\x61tures.proto\x12\x11zeyro.features.v1\"X\n\x17\x46\x65\x61tureRecomputeRequest\x12\x15\n\ruser_ref_hash\x18\x01 \x01(\t\x12\x0e\n\x06window\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65\x61ture_groups\x18\x03 \x03(\t\"m\n\rFeatureRecord\x12\x15\n\rfeature_group\x18\x01 \x01(\t\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x02 \x01(\t\x12\x1a\n\x12\x66\x65\x61ture_value_json\x18\x03 \x01(\t\x12\x13\n\x0b\x63omputed_at\x18\x04 \x01(\t\"k\n\x0f\x46\x65\x61tureResponse\x12\x15\n\ruser_ref_hash\x18\x01 \x01(\t\x12\x0e\n\x06window\x18\x02 \x01(\t\x12\x31\n\x07records\x18\x03 \x03(\x0b\x32 .zeyro.features.v1.FeatureRecord2\xd4\x01\n\x0e\x46\x65\x61tureService\x12\x63\n\x11RecomputeFeatures\x12*.zeyro.features.v1.FeatureRecomputeRequest\x1a\".zeyro.features.v1.FeatureResponse\x12]\n\x0bGetFeatures\x12*.zeyro.features.v1.FeatureRecomputeRequest\x1a\".zeyro.features.v1.FeatureResponseB;Z9github.com/arthazeyro/zeyro-b2b/proto/features;featurespbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'features_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/arthazeyro/zeyro-b2b/proto/features;featurespb'
  _globals['_FEATURERECOMPUTEREQUEST']._serialized_start=37
  _globals['_FEATURERECOMPUTEREQUEST']._serialized_end=125
  _globals['_FEATURERECORD']._serialized_start=127
  _globals['_FEATURERECORD']._serialized_end=236
  _globals['_FEATURERESPONSE']._serialized_start=238
  _globals['_FEATURERESPONSE']._serialized_end=345
  _globals['_FEATURESERVICE']._serialized_start=348
  _globals['_FEATURESERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
