# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scoring.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscoring.proto\x12\x10zeyro.scoring.v1\"b\n\x0cScoreRequest\x12\x12\n\npartner_id\x18\x01 \x01(\t\x12\x15\n\ruser_ref_hash\x18\x02 \x01(\t\x12\x10\n\x08products\x18\x03 \x03(\t\x12\x15\n\rscore_version\x18\x04 \x01(\t\"@\n\x0bScoreFactor\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06impact\x18\x03 \x01(\x01\"l\n\x0bScoreResult\x12\x0f\n\x07product\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12.\n\x07\x66\x61\x63tors\x18\x04 \x03(\x0b\x32\x1d.zeyro.scoring.v1.ScoreFactor\"m\n\rScoreResponse\x12\x15\n\ruser_ref_hash\x18\x01 \x01(\t\x12\x15\n\rscore_version\x18\x02 \x01(\t\x12.\n\x07results\x18\x03 \x03(\x0b\x32\x1d.zeyro.scoring.v1.ScoreResult2^\n\x0eScoringService\x12L\n\tGetScores\x12\x1e.zeyro.scoring.v1.ScoreRequest\x1a\x1f.zeyro.scoring.v1.ScoreResponseB9Z7github.com/arthazeyro/zeyro-b2b/proto/scoring;scoringpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/arthazeyro/zeyro-b2b/proto/scoring;scoringpb'
  _globals['_SCOREREQUEST']._serialized_start=35
  _globals['_SCOREREQUEST']._serialized_end=133
  _globals['_SCOREFACTOR']._serialized_start=135
  _globals['_SCOREFACTOR']._serialized_end=199
  _globals['_SCORERESULT']._serialized_start=201
  _globals['_SCORERESULT']._serialized_end=309
  _globals['_SCORERESPONSE']._serialized_start=311
  _globals['_SCORERESPONSE']._serialized_end=420
  _globals['_SCORINGSERVICE']._serialized_start=422
  _globals['_SCORINGSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
