// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/audit.proto

package auditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PartnerId     string                 `protobuf:"bytes,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	ActorType     string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorRef      string                 `protobuf:"bytes,4,opt,name=actor_ref,json=actorRef,proto3" json:"actor_ref,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceRef   string                 `protobuf:"bytes,6,opt,name=resource_ref,json=resourceRef,proto3" json:"resource_ref,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,8,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEventRequest) Reset() {
	*x = AuditEventRequest{}
	mi := &file_proto_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEventRequest) ProtoMessage() {}

func (x *AuditEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEventRequest.ProtoReflect.Descriptor instead.
func (*AuditEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEventRequest) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *AuditEventRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *AuditEventRequest) GetActorRef() string {
	if x != nil {
		return x.ActorRef
	}
	return ""
}

func (x *AuditEventRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditEventRequest) GetResourceRef() string {
	if x != nil {
		return x.ResourceRef
	}
	return ""
}

func (x *AuditEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuditEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type AuditEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEventResponse) Reset() {
	*x = AuditEventResponse{}
	mi := &file_proto_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEventResponse) ProtoMessage() {}

func (x *AuditEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEventResponse.ProtoReflect.Descriptor instead.
func (*AuditEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuditEventResponse) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

var File_proto_audit_proto protoreflect.FileDescriptor

const file_proto_audit_proto_rawDesc = "" +
	"\n" +
	"\x11proto/audit.proto\x12\x0ezeyro.audit.v1\"\x90\x02\n" +
	"\x11AuditEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"partner_id\x18\x02 \x01(\tR\tpartnerId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\x12\x1b\n" +
	"\tactor_ref\x18\x04 \x01(\tR\bactorRef\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\x12!\n" +
	"\fresource_ref\x18\x06 \x01(\tR\vresourceRef\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fpayload_json\x18\b \x01(\tR\vpayloadJson\"P\n" +
	"\x12AuditEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\voccurred_at\x18\x02 \x01(\tR\n" +
	"occurredAt2h\n" +
	"\fAuditService\x12X\n" +
	"\x0fWriteAuditEvent\x12!.zeyro.audit.v1.AuditEventRequest\x1a\".zeyro.audit.v1.AuditEventResponseB5Z3github.com/arthazeyro/zeyro-b2b/proto/audit;auditpbb\x06proto3"

var (
	file_proto_audit_proto_rawDescOnce sync.Once
	file_proto_audit_proto_rawDescData []byte
)

func file_proto_audit_proto_rawDescGZIP() []byte {
	file_proto_audit_proto_rawDescOnce.Do(func() {
		file_proto_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_audit_proto_rawDesc), len(file_proto_audit_proto_rawDesc)))
	})
	return file_proto_audit_proto_rawDescData
}

var file_proto_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_audit_proto_goTypes = []any{
	(*AuditEventRequest)(nil),  // 0: zeyro.audit.v1.AuditEventRequest
	(*AuditEventResponse)(nil), // 1: zeyro.audit.v1.AuditEventResponse
}
var file_proto_audit_proto_depIdxs = []int32{
	0, // 0: zeyro.audit.v1.AuditService.WriteAuditEvent:input_type -> zeyro.audit.v1.AuditEventRequest
	1, // 1: zeyro.audit.v1.AuditService.WriteAuditEvent:output_type -> zeyro.audit.v1.AuditEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_audit_proto_init() }
func file_proto_audit_proto_init() {
	if File_proto_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_audit_proto_rawDesc), len(file_proto_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_audit_proto_goTypes,
		DependencyIndexes: file_proto_audit_proto_depIdxs,
		MessageInfos:      file_proto_audit_proto_msgTypes,
	}.Build()
	File_proto_audit_proto = out.File
	file_proto_audit_proto_goTypes = nil
	file_proto_audit_proto_depIdxs = nil
}
