// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/consent.proto

package consentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsentService_InitiateConsent_FullMethodName  = "/zeyro.consent.v1.ConsentService/InitiateConsent"
	ConsentService_GetConsentStatus_FullMethodName = "/zeyro.consent.v1.ConsentService/GetConsentStatus"
)

// ConsentServiceClient is the client API for ConsentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsentServiceClient interface {
	InitiateConsent(ctx context.Context, in *ConsentInitiateRequest, opts ...grpc.CallOption) (*ConsentResponse, error)
	GetConsentStatus(ctx context.Context, in *ConsentStatusRequest, opts ...grpc.CallOption) (*ConsentResponse, error)
}

type consentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsentServiceClient(cc grpc.ClientConnInterface) ConsentServiceClient {
	return &consentServiceClient{cc}
}

func (c *consentServiceClient) InitiateConsent(ctx context.Context, in *ConsentInitiateRequest, opts ...grpc.CallOption) (*ConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsentResponse)
	err := c.cc.Invoke(ctx, ConsentService_InitiateConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) GetConsentStatus(ctx context.Context, in *ConsentStatusRequest, opts ...grpc.CallOption) (*ConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsentResponse)
	err := c.cc.Invoke(ctx, ConsentService_GetConsentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsentServiceServer is the server API for ConsentService service.
// All implementations must embed UnimplementedConsentServiceServer
// for forward compatibility.
type ConsentServiceServer interface {
	InitiateConsent(context.Context, *ConsentInitiateRequest) (*ConsentResponse, error)
	GetConsentStatus(context.Context, *ConsentStatusRequest) (*ConsentResponse, error)
	mustEmbedUnimplementedConsentServiceServer()
}

// UnimplementedConsentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsentServiceServer struct{}

func (UnimplementedConsentServiceServer) InitiateConsent(context.Context, *ConsentInitiateRequest) (*ConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateConsent not implemented")
}
func (UnimplementedConsentServiceServer) GetConsentStatus(context.Context, *ConsentStatusRequest) (*ConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsentStatus not implemented")
}
func (UnimplementedConsentServiceServer) mustEmbedUnimplementedConsentServiceServer() {}
func (UnimplementedConsentServiceServer) testEmbeddedByValue()                        {}

// UnsafeConsentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsentServiceServer will
// result in compilation errors.
type UnsafeConsentServiceServer interface {
	mustEmbedUnimplementedConsentServiceServer()
}

func RegisterConsentServiceServer(s grpc.ServiceRegistrar, srv ConsentServiceServer) {
	// If the following call panics, it indicates UnimplementedConsentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsentService_ServiceDesc, srv)
}

func _ConsentService_InitiateConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsentInitiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).InitiateConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_InitiateConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).InitiateConsent(ctx, req.(*ConsentInitiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_GetConsentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).GetConsentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_GetConsentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).GetConsentStatus(ctx, req.(*ConsentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsentService_ServiceDesc is the grpc.ServiceDesc for ConsentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zeyro.consent.v1.ConsentService",
	HandlerType: (*ConsentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateConsent",
			Handler:    _ConsentService_InitiateConsent_Handler,
		},
		{
			MethodName: "GetConsentStatus",
			Handler:    _ConsentService_GetConsentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consent.proto",
}
