// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/consent.proto

package consentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsentInitiateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartnerId     string                 `protobuf:"bytes,1,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	UserRefHash   string                 `protobuf:"bytes,2,opt,name=user_ref_hash,json=userRefHash,proto3" json:"user_ref_hash,omitempty"`
	PurposeCode   string                 `protobuf:"bytes,3,opt,name=purpose_code,json=purposeCode,proto3" json:"purpose_code,omitempty"`
	DataFrom      string                 `protobuf:"bytes,4,opt,name=data_from,json=dataFrom,proto3" json:"data_from,omitempty"`
	DataTo        string                 `protobuf:"bytes,5,opt,name=data_to,json=dataTo,proto3" json:"data_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsentInitiateRequest) Reset() {
	*x = ConsentInitiateRequest{}
	mi := &file_proto_consent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentInitiateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentInitiateRequest) ProtoMessage() {}

func (x *ConsentInitiateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentInitiateRequest.ProtoReflect.Descriptor instead.
func (*ConsentInitiateRequest) Descriptor() ([]byte, []int) {
	return file_proto_consent_proto_rawDescGZIP(), []int{0}
}

func (x *ConsentInitiateRequest) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *ConsentInitiateRequest) GetUserRefHash() string {
	if x != nil {
		return x.UserRefHash
	}
	return ""
}

func (x *ConsentInitiateRequest) GetPurposeCode() string {
	if x != nil {
		return x.PurposeCode
	}
	return ""
}

func (x *ConsentInitiateRequest) GetDataFrom() string {
	if x != nil {
		return x.DataFrom
	}
	return ""
}

func (x *ConsentInitiateRequest) GetDataTo() string {
	if x != nil {
		return x.DataTo
	}
	return ""
}

type ConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsentId     string                 `protobuf:"bytes,1,opt,name=consent_id,json=consentId,proto3" json:"consent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsentResponse) Reset() {
	*x = ConsentResponse{}
	mi := &file_proto_consent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentResponse) ProtoMessage() {}

func (x *ConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentResponse.ProtoReflect.Descriptor instead.
func (*ConsentResponse) Descriptor() ([]byte, []int) {
	return file_proto_consent_proto_rawDescGZIP(), []int{1}
}

func (x *ConsentResponse) GetConsentId() string {
	if x != nil {
		return x.ConsentId
	}
	return ""
}

func (x *ConsentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConsentResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ConsentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsentId     string                 `protobuf:"bytes,1,opt,name=consent_id,json=consentId,proto3" json:"consent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsentStatusRequest) Reset() {
	*x = ConsentStatusRequest{}
	mi := &file_proto_consent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentStatusRequest) ProtoMessage() {}

func (x *ConsentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentStatusRequest.ProtoReflect.Descriptor instead.
func (*ConsentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_consent_proto_rawDescGZIP(), []int{2}
}

func (x *ConsentStatusRequest) GetConsentId() string {
	if x != nil {
		return x.ConsentId
	}
	return ""
}

var File_proto_consent_proto protoreflect.FileDescriptor

const file_proto_consent_proto_rawDesc = "" +
	"\n" +
	"\x13proto/consent.proto\x12\x10zeyro.consent.v1\"\xb4\x01\n" +
	"\x16ConsentInitiateRequest\x12\x1d\n" +
	"\n" +
	"partner_id\x18\x01 \x01(\tR\tpartnerId\x12\"\n" +
	"\ruser_ref_hash\x18\x02 \x01(\tR\vuserRefHash\x12!\n" +
	"\fpurpose_code\x18\x03 \x01(\tR\vpurposeCode\x12\x1b\n" +
	"\tdata_from\x18\x04 \x01(\tR\bdataFrom\x12\x17\n" +
	"\adata_to\x18\x05 \x01(\tR\x06dataTo\"g\n" +
	"\x0fConsentResponse\x12\x1d\n" +
	"\n" +
	"consent_id\x18\x01 \x01(\tR\tconsentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"5\n" +
	"\x14ConsentStatusRequest\x12\x1d\n" +
	"\n" +
	"consent_id\x18\x01 \x01(\tR\tconsentId2\xcf\x01\n" +
	"\x0eConsentService\x12^\n" +
	"\x0fInitiateConsent\x12(.zeyro.consent.v1.ConsentInitiateRequest\x1a!.zeyro.consent.v1.ConsentResponse\x12]\n" +
	"\x10GetConsentStatus\x12&.zeyro.consent.v1.ConsentStatusRequest\x1a!.zeyro.consent.v1.ConsentResponseB9Z7github.com/arthazeyro/zeyro-b2b/proto/consent;consentpbb\x06proto3"

var (
	file_proto_consent_proto_rawDescOnce sync.Once
	file_proto_consent_proto_rawDescData []byte
)

func file_proto_consent_proto_rawDescGZIP() []byte {
	file_proto_consent_proto_rawDescOnce.Do(func() {
		file_proto_consent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consent_proto_rawDesc), len(file_proto_consent_proto_rawDesc)))
	})
	return file_proto_consent_proto_rawDescData
}

var file_proto_consent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_consent_proto_goTypes = []any{
	(*ConsentInitiateRequest)(nil), // 0: zeyro.consent.v1.ConsentInitiateRequest
	(*ConsentResponse)(nil),        // 1: zeyro.consent.v1.ConsentResponse
	(*ConsentStatusRequest)(nil),   // 2: zeyro.consent.v1.ConsentStatusRequest
}
var file_proto_consent_proto_depIdxs = []int32{
	0, // 0: zeyro.consent.v1.ConsentService.InitiateConsent:input_type -> zeyro.consent.v1.ConsentInitiateRequest
	2, // 1: zeyro.consent.v1.ConsentService.GetConsentStatus:input_type -> zeyro.consent.v1.ConsentStatusRequest
	1, // 2: zeyro.consent.v1.ConsentService.InitiateConsent:output_type -> zeyro.consent.v1.ConsentResponse
	1, // 3: zeyro.consent.v1.ConsentService.GetConsentStatus:output_type -> zeyro.consent.v1.ConsentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_consent_proto_init() }
func file_proto_consent_proto_init() {
	if File_proto_consent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consent_proto_rawDesc), len(file_proto_consent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consent_proto_goTypes,
		DependencyIndexes: file_proto_consent_proto_depIdxs,
		MessageInfos:      file_proto_consent_proto_msgTypes,
	}.Build()
	File_proto_consent_proto = out.File
	file_proto_consent_proto_goTypes = nil
	file_proto_consent_proto_depIdxs = nil
}
