import logging
import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

def extract_baseline(df: pd.DataFrame, feature_cols: list[str], max_bins: int = 10, max_categories: int = 20) -> dict:
    """
    Extract baseline distributions for PSI calculation.
    
    Args:
        df: The baseline DataFrame (e.g., Training set).
        feature_cols: List of feature columns to extract.
        max_bins: Maximum number of quantiles for continuous variables.
        max_categories: Maximum number of categories for discrete variables.
    """
    baseline = {}
    total_rows = len(df)
    if total_rows == 0:
        return baseline
        
    for col in feature_cols:
        if col not in df.columns:
            continue
            
        series = df[col]
        missing_count = series.isna().sum()
        missing_prop = missing_count / total_rows
        
        series_clean = series.dropna()
        valid_count = len(series_clean)
        
        # Determine type
        # If object/string or nunique <= max_categories, treat as categorical
        nunique = series_clean.nunique()
        is_object = pd.api.types.is_object_dtype(series_clean) or pd.api.types.is_string_dtype(series_clean)
        
        if valid_count == 0:
            # If all missing
            baseline[col] = {
                "type": "categorical",
                "categories": ["Other", "Missing"],
                "proportions": [0.0, 1.0],
                "realized_bins": 0
            }
            continue
            
        if not is_object and nunique > max_categories:
            # Continuous
            # retbins=True gives us the exact edges
            # duplicates='drop' prevents crashes on skewed distributions where quantiles tie
            _, bin_edges = pd.qcut(series_clean, q=max_bins, retbins=True, duplicates='drop')
            realized_bins = len(bin_edges) - 1
            
            # Widen the outer edges to catch unseen data in the future
            # Using 1e99 instead of np.inf for clean JSON serialization
            bin_edges[0] = -1e99
            bin_edges[-1] = 1e99
            
            counts = pd.cut(series_clean, bins=[float(x) for x in bin_edges]).value_counts(sort=False).values
            proportions = [float(c) / total_rows for c in counts]
            proportions.append(float(missing_prop)) # Missing is the last bucket
            
            baseline[col] = {
                "type": "continuous",
                "edges": bin_edges.tolist(),
                "proportions": proportions,
                "realized_bins": realized_bins
            }
        else:
            # Categorical
            val_counts = series_clean.value_counts()
            top_cats = val_counts.head(max_categories)
            other_count = val_counts.iloc[max_categories:].sum() if len(val_counts) > max_categories else 0
            
            categories = top_cats.index.tolist()
            proportions = [float(c) / total_rows for c in top_cats]
            
            categories.append("Other")
            proportions.append(other_count / total_rows)
            
            categories.append("Missing")
            proportions.append(float(missing_prop))
            
            baseline[col] = {
                "type": "categorical",
                "categories": categories,
                "proportions": proportions,
                "realized_bins": len(top_cats)
            }
            
    return baseline

def calculate_psi(baseline: dict, new_df: pd.DataFrame, epsilon: float = 1e-4) -> dict:
    """
    Calculate Population Stability Index (PSI) against a frozen baseline.
    
    Args:
        baseline: The baseline dictionary generated by extract_baseline.
        new_df: The new scoring DataFrame.
        epsilon: 1e-4 is the industry standard for 10-bin PSI calculation.
                 We add this uniformly to all buckets (base and new) and re-normalize 
                 to prevent log(0) errors and mathematically stabilize empty buckets.
    """
    psi_scores = {}
    total_rows = len(new_df)
    
    if total_rows == 0:
        return psi_scores
        
    for col, b_info in baseline.items():
        if col not in new_df.columns:
            logger.warning(f"[PSI] Column {col} missing in new_df.")
            continue
            
        series = new_df[col]
        missing_count = series.isna().sum()
        missing_prop = missing_count / total_rows
        
        series_clean = series.dropna()
        
        base_props = np.array(b_info["proportions"], dtype=float)
        
        if b_info["type"] == "continuous":
            edges = b_info["edges"]
            realized_bins = b_info["realized_bins"]
            
            if realized_bins < 3:
                logger.warning(f"[PSI] Feature {col} has suspiciously small realized bins ({realized_bins}). Check for extreme skew.")
                
            counts = pd.cut(series_clean, bins=edges).value_counts(sort=False).values
            new_props = (counts / total_rows).tolist()
            new_props.append(float(missing_prop))
            new_props = np.array(new_props, dtype=float)
            
        else:
            categories = b_info["categories"]
            # categories[-2] is "Other", categories[-1] is "Missing"
            tracked_cats = set(categories[:-2])
            
            # Count tracked
            counts = series_clean.value_counts()
            
            new_props = []
            other_count = 0
            
            for cat in categories[:-2]:
                new_props.append(counts.get(cat, 0) / total_rows)
                
            # Any category in new data NOT in tracked_cats goes to Other
            for cat, count in counts.items():
                if cat not in tracked_cats:
                    other_count += count
                    
            new_props.append(other_count / total_rows)
            new_props.append(float(missing_prop))
            
            new_props = np.array(new_props, dtype=float)
            
        # Apply Epsilon Uniformly + Renormalize
        base_props = base_props + epsilon
        base_props = base_props / base_props.sum()
        
        new_props = new_props + epsilon
        new_props = new_props / new_props.sum()
        
        # Calculate PSI
        psi = np.sum((new_props - base_props) * np.log(new_props / base_props))
        psi_scores[col] = float(psi)
        
    return psi_scores
