"""Model Registry — versioned artefact store for all trained models.

Responsibilities:
  1. Assign a monotonic integer version to every model run.
  2. Write a structured MANIFEST.md in the artefact directory.
  3. Snapshot SHAP importance diffs between the current and previous version.
  4. Expose a `promote` method that marks a version as "production".
  5. Expose a `rollback` method that demotes production back to the prior version.

Directory layout (under artifacts/<model_name>/):
    v1/
        model.json
        calibrator.pkl
        metrics.json
        shap_importance.json
        MANIFEST.md             ← generated by this module
    v2/
        ...
    registry.json               ← single source of truth for current/latest versions
    CHANGELOG.md                ← append-only log of all version promotions

Usage from a notebook:
    from training import ModelRegistry
    reg = ModelRegistry("bfs")
    reg.register(result, training_rows=50_000, target_rate=0.08)
    reg.promote(version=2)
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_ARTIFACT_ROOT = Path(__file__).parent.parent.parent / "artifacts"

# Gate thresholds — mirrors model_card.py
_AUC_GATE: float = 0.72
_BRIER_GATE: float = 0.15


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class VersionEntry:
    version: int
    run_name: str
    trained_at: str
    training_rows: int
    target_rate: float
    auc: float | None
    brier: float | None
    calibration_passed: bool
    promoted: bool = False
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.version,
            "run_name": self.run_name,
            "trained_at": self.trained_at,
            "training_rows": self.training_rows,
            "target_rate": self.target_rate,
            "auc": self.auc,
            "brier": self.brier,
            "calibration_passed": self.calibration_passed,
            "promoted": self.promoted,
            "notes": self.notes,
        }

    @staticmethod
    def from_dict(d: dict[str, Any]) -> "VersionEntry":
        return VersionEntry(**d)


@dataclass
class Registry:
    model_name: str
    production_version: int | None = None
    latest_version: int = 0
    versions: list[VersionEntry] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "model_name": self.model_name,
            "production_version": self.production_version,
            "latest_version": self.latest_version,
            "versions": [v.to_dict() for v in self.versions],
        }

    @staticmethod
    def from_dict(d: dict[str, Any]) -> "Registry":
        versions = [VersionEntry.from_dict(v) for v in d.get("versions", [])]
        return Registry(
            model_name=d["model_name"],
            production_version=d.get("production_version"),
            latest_version=d.get("latest_version", 0),
            versions=versions,
        )


# ---------------------------------------------------------------------------
# ModelRegistry
# ---------------------------------------------------------------------------

class ModelRegistry:
    """
    Versioned model registry for a single model type (BFS, RPS).

    All state is persisted to:
      artifacts/<model_name>/registry.json
      artifacts/<model_name>/CHANGELOG.md
    """

    def __init__(self, model_name: str, root: Path | None = None) -> None:
        self.model_name = model_name.lower()
        self.root = (root or _ARTIFACT_ROOT) / self.model_name
        self.root.mkdir(parents=True, exist_ok=True)
        self._registry_path = self.root / "registry.json"
        self._changelog_path = self.root / "CHANGELOG.md"
        self._state = self._load()

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _load(self) -> Registry:
        if self._registry_path.exists():
            try:
                return Registry.from_dict(json.loads(self._registry_path.read_text()))
            except (json.JSONDecodeError, KeyError) as exc:
                logger.warning("Corrupt registry.json, starting fresh: %s", exc)
        return Registry(model_name=self.model_name)

    def _save(self) -> None:
        self._registry_path.write_text(
            json.dumps(self._state.to_dict(), indent=2)
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def register(
        self,
        result: dict,
        training_rows: int,
        target_rate: float,
        notes: str = "",
    ) -> int:
        """
        Register a completed training run and return its version number.

        Writes MANIFEST.md into the run artefact directory and appends a
        SHAP diff section comparing to the previous version.

        Args:
            result: Dict returned by any train_*.run() function.
            training_rows: Total rows in the training dataset.
            target_rate: Positive-class rate in the training dataset.
            notes: Free-text notes for this run.

        Returns:
            The new version integer.
        """
        new_version = self._state.latest_version + 1
        trained_at = datetime.now(timezone.utc).isoformat()

        metrics = result.get("metrics", {})
        cal = metrics.get("calibrated", metrics)

        entry = VersionEntry(
            version=new_version,
            run_name=result.get("run_name", f"{self.model_name}_v{new_version}"),
            trained_at=trained_at,
            training_rows=training_rows,
            target_rate=target_rate,
            auc=cal.get("auc"),
            brier=cal.get("brier"),
            calibration_passed=result.get("calibration_passed", True),
            notes=notes,
        )

        self._state.versions.append(entry)
        self._state.latest_version = new_version
        self._save()

        # Write human-readable MANIFEST.md inside the run directory
        run_dir = self.root / result.get("run_name", f"v{new_version}")
        if run_dir.exists():
            self._write_manifest(run_dir, entry, result)

        logger.info("[%s] Registered version %d", self.model_name.upper(), new_version)
        return new_version

    def promote(self, version: int) -> None:
        """
        Mark a specific version as the production model.

        Validates deployment gates before promoting.

        Args:
            version: Version number to promote.

        Raises:
            ValueError: If the version doesn't exist or fails deployment gates.
        """
        entry = self._get_entry(version)

        # Gate checks
        auc_ok = (entry.auc is None) or (entry.auc >= _AUC_GATE)
        brier_ok = (entry.brier is None) or (entry.brier <= _BRIER_GATE)
        if not auc_ok:
            raise ValueError(
                f"Version {version} AUC {entry.auc:.4f} < gate {_AUC_GATE}. "
                "Retrain or override manually."
            )
        if not brier_ok:
            raise ValueError(
                f"Version {version} Brier {entry.brier:.4f} > gate {_BRIER_GATE}. "
                "Recalibrate or override manually."
            )
        if not entry.calibration_passed:
            raise ValueError(
                f"Version {version} failed calibration gate. "
                "Run fit_calibrator() again with more calibration data."
            )

        previous = self._state.production_version
        self._state.production_version = version
        entry.promoted = True
        self._save()

        self._append_changelog(
            action="PROMOTE",
            version=version,
            previous=previous,
            entry=entry,
        )
        print(
            f"[{self.model_name.upper()}] ✅ Version {version} promoted to production "
            f"(replaced v{previous})."
        )

    def rollback(self) -> int:
        """
        Roll back production to the previous promoted version.

        Returns:
            The version number rolled back to.

        Raises:
            RuntimeError: If there is no prior promoted version to roll back to.
        """
        promoted = [v for v in self._state.versions if v.promoted]
        if len(promoted) < 2:
            raise RuntimeError("No prior promoted version available for rollback.")

        current = promoted[-1]
        previous = promoted[-2]

        self._state.production_version = previous.version
        current.promoted = False
        self._save()

        self._append_changelog(
            action="ROLLBACK",
            version=previous.version,
            previous=current.version,
            entry=previous,
        )
        print(
            f"[{self.model_name.upper()}] ⏪ Rolled back from v{current.version} "
            f"to v{previous.version}."
        )
        return previous.version

    def list_versions(self) -> list[dict]:
        """Return all registered versions as a list of dicts."""
        return [v.to_dict() for v in self._state.versions]

    def production_path(self) -> Path | None:
        """Return the artefact directory for the current production version."""
        if self._state.production_version is None:
            return None
        prod = self._get_entry(self._state.production_version)
        return self.root / prod.run_name

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_entry(self, version: int) -> VersionEntry:
        for v in self._state.versions:
            if v.version == version:
                return v
        raise ValueError(f"Version {version} not found in registry for {self.model_name}.")

    def _write_manifest(
        self,
        run_dir: Path,
        entry: VersionEntry,
        result: dict,
    ) -> None:
        """Write MANIFEST.md inside the run artefact directory."""
        previous_shap = self._get_previous_shap()
        current_shap: dict[str, float] = result.get("shap_importance", {})

        shap_diff_section = _format_shap_diff(previous_shap, current_shap)
        metrics = result.get("metrics", {})

        manifest = f"""# Model Manifest — {self.model_name.upper()} v{entry.version}

| Field | Value |
|-------|-------|
| **Run name** | `{entry.run_name}` |
| **Trained at** | {entry.trained_at} |
| **Training rows** | {entry.training_rows:,} |
| **Target rate** | {entry.target_rate:.2%} |
| **AUC (calibrated)** | {entry.auc if entry.auc is not None else "N/A"} |
| **Brier score** | {entry.brier if entry.brier is not None else "N/A"} |
| **Calibration gate** | {"✅ PASS" if entry.calibration_passed else "❌ FAIL"} |
| **Notes** | {entry.notes or "—"} |

## Evaluation Metrics

```json
{json.dumps(metrics, indent=2)}
```

## SHAP Feature Importance (Top 10)

| Rank | Feature | Mean |SHAP| |
|------|---------|------------|
{_format_shap_table(current_shap)}

{shap_diff_section}
"""
        (run_dir / "MANIFEST.md").write_text(manifest)
        logger.debug("Wrote MANIFEST.md to %s", run_dir)

    def _get_previous_shap(self) -> dict[str, float]:
        """Load SHAP importance from the most recent prior version, if any."""
        prior = [v for v in self._state.versions[:-1]]  # exclude the just-registered one
        if not prior:
            return {}
        last = prior[-1]
        shap_path = self.root / last.run_name / "shap_importance.json"
        if shap_path.exists():
            try:
                return json.loads(shap_path.read_text())
            except json.JSONDecodeError:
                pass
        return {}

    def _append_changelog(
        self,
        action: str,
        version: int,
        previous: int | None,
        entry: VersionEntry,
    ) -> None:
        """Append a record to CHANGELOG.md."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        auc_str = f"{entry.auc:.4f}" if entry.auc is not None else "N/A"
        brier_str = f"{entry.brier:.4f}" if entry.brier is not None else "N/A"

        record = (
            f"\n## [{action}] v{version} — {timestamp}\n"
            f"- **Previous production**: v{previous}\n"
            f"- **AUC**: {auc_str} | **Brier**: {brier_str}\n"
            f"- **Calibration**: {'PASS' if entry.calibration_passed else 'FAIL'}\n"
            f"- **Notes**: {entry.notes or '—'}\n"
        )

        if not self._changelog_path.exists():
            self._changelog_path.write_text(
                f"# {self.model_name.upper()} Model Changelog\n\n"
                "_Append-only log of all version promotions and rollbacks._\n"
            )

        with open(self._changelog_path, "a") as f:
            f.write(record)


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _format_shap_table(shap: dict[str, float], top_n: int = 10) -> str:
    rows = list(shap.items())[:top_n]
    lines = []
    for i, (feat, val) in enumerate(rows, 1):
        lines.append(f"| {i} | `{feat}` | {val:.6f} |")
    return "\n".join(lines) if lines else "| — | No SHAP data | — |"


def _format_shap_diff(
    previous: dict[str, float],
    current: dict[str, float],
    top_n: int = 10,
) -> str:
    if not previous:
        return "_No prior version available for SHAP diff._\n"

    lines = [
        "## SHAP Weight Diff (vs Previous Version)\n",
        "| Feature | Previous | Current | Δ |",
        "|---------|----------|---------|---|",
    ]
    all_features = dict.fromkeys(list(current.keys())[:top_n])
    for feat in all_features:
        prev_val = previous.get(feat, 0.0)
        curr_val = current.get(feat, 0.0)
        delta = curr_val - prev_val
        sign = "▲" if delta > 0 else ("▼" if delta < 0 else "–")
        lines.append(
            f"| `{feat}` | {prev_val:.6f} | {curr_val:.6f} | {sign} {abs(delta):.6f} |"
        )
    return "\n".join(lines)
