// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/scoring.proto

package scoringpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartnerId     string                 `protobuf:"bytes,1,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	UserRefHash   string                 `protobuf:"bytes,2,opt,name=user_ref_hash,json=userRefHash,proto3" json:"user_ref_hash,omitempty"`
	Products      []string               `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	ScoreVersion  string                 `protobuf:"bytes,4,opt,name=score_version,json=scoreVersion,proto3" json:"score_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_proto_scoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoring_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreRequest) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *ScoreRequest) GetUserRefHash() string {
	if x != nil {
		return x.UserRefHash
	}
	return ""
}

func (x *ScoreRequest) GetProducts() []string {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ScoreRequest) GetScoreVersion() string {
	if x != nil {
		return x.ScoreVersion
	}
	return ""
}

type ScoreFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Impact        float64                `protobuf:"fixed64,3,opt,name=impact,proto3" json:"impact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreFactor) Reset() {
	*x = ScoreFactor{}
	mi := &file_proto_scoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreFactor) ProtoMessage() {}

func (x *ScoreFactor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreFactor.ProtoReflect.Descriptor instead.
func (*ScoreFactor) Descriptor() ([]byte, []int) {
	return file_proto_scoring_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreFactor) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ScoreFactor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScoreFactor) GetImpact() float64 {
	if x != nil {
		return x.Impact
	}
	return 0
}

type ScoreResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Factors       []*ScoreFactor         `protobuf:"bytes,4,rep,name=factors,proto3" json:"factors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResult) Reset() {
	*x = ScoreResult{}
	mi := &file_proto_scoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResult) ProtoMessage() {}

func (x *ScoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResult.ProtoReflect.Descriptor instead.
func (*ScoreResult) Descriptor() ([]byte, []int) {
	return file_proto_scoring_proto_rawDescGZIP(), []int{2}
}

func (x *ScoreResult) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *ScoreResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ScoreResult) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ScoreResult) GetFactors() []*ScoreFactor {
	if x != nil {
		return x.Factors
	}
	return nil
}

type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRefHash   string                 `protobuf:"bytes,1,opt,name=user_ref_hash,json=userRefHash,proto3" json:"user_ref_hash,omitempty"`
	ScoreVersion  string                 `protobuf:"bytes,2,opt,name=score_version,json=scoreVersion,proto3" json:"score_version,omitempty"`
	Results       []*ScoreResult         `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_proto_scoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoring_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreResponse) GetUserRefHash() string {
	if x != nil {
		return x.UserRefHash
	}
	return ""
}

func (x *ScoreResponse) GetScoreVersion() string {
	if x != nil {
		return x.ScoreVersion
	}
	return ""
}

func (x *ScoreResponse) GetResults() []*ScoreResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_scoring_proto protoreflect.FileDescriptor

const file_proto_scoring_proto_rawDesc = "" +
	"\n" +
	"\x13proto/scoring.proto\x12\x10zeyro.scoring.v1\"\x92\x01\n" +
	"\fScoreRequest\x12\x1d\n" +
	"\n" +
	"partner_id\x18\x01 \x01(\tR\tpartnerId\x12\"\n" +
	"\ruser_ref_hash\x18\x02 \x01(\tR\vuserRefHash\x12\x1a\n" +
	"\bproducts\x18\x03 \x03(\tR\bproducts\x12#\n" +
	"\rscore_version\x18\x04 \x01(\tR\fscoreVersion\"[\n" +
	"\vScoreFactor\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06impact\x18\x03 \x01(\x01R\x06impact\"\x8c\x01\n" +
	"\vScoreResult\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x127\n" +
	"\afactors\x18\x04 \x03(\v2\x1d.zeyro.scoring.v1.ScoreFactorR\afactors\"\x91\x01\n" +
	"\rScoreResponse\x12\"\n" +
	"\ruser_ref_hash\x18\x01 \x01(\tR\vuserRefHash\x12#\n" +
	"\rscore_version\x18\x02 \x01(\tR\fscoreVersion\x127\n" +
	"\aresults\x18\x03 \x03(\v2\x1d.zeyro.scoring.v1.ScoreResultR\aresults2^\n" +
	"\x0eScoringService\x12L\n" +
	"\tGetScores\x12\x1e.zeyro.scoring.v1.ScoreRequest\x1a\x1f.zeyro.scoring.v1.ScoreResponseB9Z7github.com/arthazeyro/zeyro-b2b/proto/scoring;scoringpbb\x06proto3"

var (
	file_proto_scoring_proto_rawDescOnce sync.Once
	file_proto_scoring_proto_rawDescData []byte
)

func file_proto_scoring_proto_rawDescGZIP() []byte {
	file_proto_scoring_proto_rawDescOnce.Do(func() {
		file_proto_scoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scoring_proto_rawDesc), len(file_proto_scoring_proto_rawDesc)))
	})
	return file_proto_scoring_proto_rawDescData
}

var file_proto_scoring_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_scoring_proto_goTypes = []any{
	(*ScoreRequest)(nil),  // 0: zeyro.scoring.v1.ScoreRequest
	(*ScoreFactor)(nil),   // 1: zeyro.scoring.v1.ScoreFactor
	(*ScoreResult)(nil),   // 2: zeyro.scoring.v1.ScoreResult
	(*ScoreResponse)(nil), // 3: zeyro.scoring.v1.ScoreResponse
}
var file_proto_scoring_proto_depIdxs = []int32{
	1, // 0: zeyro.scoring.v1.ScoreResult.factors:type_name -> zeyro.scoring.v1.ScoreFactor
	2, // 1: zeyro.scoring.v1.ScoreResponse.results:type_name -> zeyro.scoring.v1.ScoreResult
	0, // 2: zeyro.scoring.v1.ScoringService.GetScores:input_type -> zeyro.scoring.v1.ScoreRequest
	3, // 3: zeyro.scoring.v1.ScoringService.GetScores:output_type -> zeyro.scoring.v1.ScoreResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scoring_proto_init() }
func file_proto_scoring_proto_init() {
	if File_proto_scoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scoring_proto_rawDesc), len(file_proto_scoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scoring_proto_goTypes,
		DependencyIndexes: file_proto_scoring_proto_depIdxs,
		MessageInfos:      file_proto_scoring_proto_msgTypes,
	}.Build()
	File_proto_scoring_proto = out.File
	file_proto_scoring_proto_goTypes = nil
	file_proto_scoring_proto_depIdxs = nil
}
