// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type AgmarknetDailyPrice struct {
	ID            string          `json:"id"`
	ArrivalDate   time.Time       `json:"arrival_date"`
	StateID       sql.NullString  `json:"state_id"`
	StateName     sql.NullString  `json:"state_name"`
	DistrictID    sql.NullString  `json:"district_id"`
	DistrictName  sql.NullString  `json:"district_name"`
	MarketID      sql.NullString  `json:"market_id"`
	MarketName    sql.NullString  `json:"market_name"`
	CommodityID   sql.NullString  `json:"commodity_id"`
	CommodityName sql.NullString  `json:"commodity_name"`
	VarietyID     sql.NullString  `json:"variety_id"`
	VarietyName   sql.NullString  `json:"variety_name"`
	GradeID       sql.NullString  `json:"grade_id"`
	GradeName     sql.NullString  `json:"grade_name"`
	MinPrice      sql.NullFloat64 `json:"min_price"`
	MaxPrice      sql.NullFloat64 `json:"max_price"`
	ModalPrice    sql.NullFloat64 `json:"modal_price"`
	Arrivals      sql.NullFloat64 `json:"arrivals"`
	PriceUnit     sql.NullString  `json:"price_unit"`
	ArrivalUnit   sql.NullString  `json:"arrival_unit"`
	Source        string          `json:"source"`
	FetchedAt     time.Time       `json:"fetched_at"`
	RawHash       string          `json:"raw_hash"`
}

type AgmarknetFilter struct {
	FilterType string    `json:"filter_type"`
	FilterID   string    `json:"filter_id"`
	FilterName string    `json:"filter_name"`
	FetchedAt  time.Time `json:"fetched_at"`
}

type Alert struct {
	ID           string         `json:"id"`
	EnterpriseID string         `json:"enterprise_id"`
	RiskLevel    sql.NullString `json:"risk_level"`
	Title        sql.NullString `json:"title"`
	Description  sql.NullString `json:"description"`
	CreatedAt    sql.NullString `json:"created_at"`
	Status       sql.NullString `json:"status"`
}

type FinancialRecord struct {
	ID               string          `json:"id"`
	EnterpriseID     string          `json:"enterprise_id"`
	Month            string          `json:"month"`
	OperatingInflow  sql.NullFloat64 `json:"operating_inflow"`
	OperatingOutflow sql.NullFloat64 `json:"operating_outflow"`
	Savings          sql.NullFloat64 `json:"savings"`
	LoanRepayment    sql.NullFloat64 `json:"loan_repayment"`
	InventoryCost    sql.NullFloat64 `json:"inventory_cost"`
	RecordedAt       string          `json:"recorded_at"`
	SyncStatus       sql.NullString  `json:"sync_status"`
}

type ForecastCache struct {
	EnterpriseID string         `json:"enterprise_id"`
	RecordHash   string         `json:"record_hash"`
	ModelVersion sql.NullString `json:"model_version"`
	ForecastJson sql.NullString `json:"forecast_json"`
	GeneratedAt  sql.NullString `json:"generated_at"`
}

type Intervention struct {
	ID                      string          `json:"id"`
	EnterpriseID            string          `json:"enterprise_id"`
	RecommendedIntervention sql.NullString  `json:"recommended_intervention"`
	IllustrativeAmount      sql.NullFloat64 `json:"illustrative_amount"`
	AssignedOfficer         sql.NullString  `json:"assigned_officer"`
	VisitDate               sql.NullString  `json:"visit_date"`
	FollowUpDate            sql.NullString  `json:"follow_up_date"`
	Notes                   sql.NullString  `json:"notes"`
	Status                  sql.NullString  `json:"status"`
	CreatedAt               sql.NullString  `json:"created_at"`
	UpdatedAt               sql.NullString  `json:"updated_at"`
}

type MarketCache struct {
	Commodity  string          `json:"commodity"`
	State      string          `json:"state"`
	Month      string          `json:"month"`
	ModalPrice sql.NullFloat64 `json:"modal_price"`
	FetchedAt  sql.NullString  `json:"fetched_at"`
}

type RiskAssessment struct {
	EnterpriseID         string          `json:"enterprise_id"`
	RiskScore            sql.NullInt64   `json:"risk_score"`
	RiskLevel            sql.NullString  `json:"risk_level"`
	ForecastDeficit      sql.NullFloat64 `json:"forecast_deficit"`
	DebtServiceShortfall sql.NullFloat64 `json:"debt_service_shortfall"`
	StressMonth          sql.NullString  `json:"stress_month"`
	WarningLeadTimeDays  sql.NullInt64   `json:"warning_lead_time_days"`
	DriversJson          sql.NullString  `json:"drivers_json"`
	AssessedAt           sql.NullString  `json:"assessed_at"`
}

type TimelineEvent struct {
	ID           string         `json:"id"`
	EnterpriseID string         `json:"enterprise_id"`
	Date         string         `json:"date"`
	Title        sql.NullString `json:"title"`
	Description  sql.NullString `json:"description"`
}

type WeatherCache struct {
	LocationKey      sql.NullString  `json:"location_key"`
	DateRange        sql.NullString  `json:"date_range"`
	DataJson         sql.NullString  `json:"data_json"`
	District         sql.NullString  `json:"district"`
	RainfallAnomaly  sql.NullFloat64 `json:"rainfall_anomaly"`
	TemperatureMean  sql.NullFloat64 `json:"temperature_mean"`
	ClimateRiskScore sql.NullFloat64 `json:"climate_risk_score"`
	FetchedAt        sql.NullString  `json:"fetched_at"`
}

type WeatherCacheV2 struct {
	CacheKey    string `json:"cache_key"`
	LocationKey string `json:"location_key"`
	RequestType string `json:"request_type"`
	PayloadJson string `json:"payload_json"`
	Source      string `json:"source"`
	FetchedAt   string `json:"fetched_at"`
	ExpiresAt   string `json:"expires_at"`
}
