// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getActiveInterventionCount = `-- name: GetActiveInterventionCount :one
SELECT COUNT(*) FROM interventions WHERE status IN ('Pending','Active')
`

func (q *Queries) GetActiveInterventionCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveInterventionCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAgmarknetFilters = `-- name: GetAgmarknetFilters :many
SELECT filter_type, filter_id, filter_name, fetched_at FROM agmarknet_filters
`

func (q *Queries) GetAgmarknetFilters(ctx context.Context) ([]AgmarknetFilter, error) {
	rows, err := q.db.QueryContext(ctx, getAgmarknetFilters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgmarknetFilter
	for rows.Next() {
		var i AgmarknetFilter
		if err := rows.Scan(
			&i.FilterType,
			&i.FilterID,
			&i.FilterName,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlerts = `-- name: GetAlerts :many
SELECT id, enterprise_id, risk_level, title, description, created_at, status
FROM alerts WHERE enterprise_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetAlerts(ctx context.Context, enterpriseID string) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, getAlerts, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.RiskLevel,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRiskAssessments = `-- name: GetAllRiskAssessments :many
SELECT enterprise_id, risk_score, risk_level, forecast_deficit, warning_lead_time_days
FROM risk_assessments
`

type GetAllRiskAssessmentsRow struct {
	EnterpriseID        string          `json:"enterprise_id"`
	RiskScore           sql.NullInt64   `json:"risk_score"`
	RiskLevel           sql.NullString  `json:"risk_level"`
	ForecastDeficit     sql.NullFloat64 `json:"forecast_deficit"`
	WarningLeadTimeDays sql.NullInt64   `json:"warning_lead_time_days"`
}

func (q *Queries) GetAllRiskAssessments(ctx context.Context) ([]GetAllRiskAssessmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllRiskAssessments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRiskAssessmentsRow
	for rows.Next() {
		var i GetAllRiskAssessmentsRow
		if err := rows.Scan(
			&i.EnterpriseID,
			&i.RiskScore,
			&i.RiskLevel,
			&i.ForecastDeficit,
			&i.WarningLeadTimeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCachedForecast = `-- name: GetCachedForecast :one
SELECT forecast_json FROM forecast_cache WHERE enterprise_id = ?
ORDER BY generated_at DESC LIMIT 1
`

func (q *Queries) GetCachedForecast(ctx context.Context, enterpriseID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getCachedForecast, enterpriseID)
	var forecast_json sql.NullString
	err := row.Scan(&forecast_json)
	return forecast_json, err
}

const getLatestAgmarknetPrices = `-- name: GetLatestAgmarknetPrices :many
SELECT id, arrival_date, state_id, state_name, district_id, district_name, market_id, market_name,
       commodity_id, commodity_name, variety_id, variety_name, grade_id, grade_name,
       min_price, max_price, modal_price, arrivals, price_unit, arrival_unit, source, fetched_at, raw_hash
FROM agmarknet_daily_prices
WHERE commodity_name = ? AND (district_name = ? OR district_name = '')
ORDER BY arrival_date DESC LIMIT ?
`

type GetLatestAgmarknetPricesParams struct {
	CommodityName sql.NullString `json:"commodity_name"`
	DistrictName  sql.NullString `json:"district_name"`
	Limit         int64          `json:"limit"`
}

func (q *Queries) GetLatestAgmarknetPrices(ctx context.Context, arg GetLatestAgmarknetPricesParams) ([]AgmarknetDailyPrice, error) {
	rows, err := q.db.QueryContext(ctx, getLatestAgmarknetPrices, arg.CommodityName, arg.DistrictName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgmarknetDailyPrice
	for rows.Next() {
		var i AgmarknetDailyPrice
		if err := rows.Scan(
			&i.ID,
			&i.ArrivalDate,
			&i.StateID,
			&i.StateName,
			&i.DistrictID,
			&i.DistrictName,
			&i.MarketID,
			&i.MarketName,
			&i.CommodityID,
			&i.CommodityName,
			&i.VarietyID,
			&i.VarietyName,
			&i.GradeID,
			&i.GradeName,
			&i.MinPrice,
			&i.MaxPrice,
			&i.ModalPrice,
			&i.Arrivals,
			&i.PriceUnit,
			&i.ArrivalUnit,
			&i.Source,
			&i.FetchedAt,
			&i.RawHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationWeatherCacheV2 = `-- name: GetLocationWeatherCacheV2 :one
SELECT cache_key, location_key, request_type, payload_json, source, fetched_at, expires_at
FROM weather_cache_v2 WHERE cache_key = ?
`

func (q *Queries) GetLocationWeatherCacheV2(ctx context.Context, cacheKey string) (WeatherCacheV2, error) {
	row := q.db.QueryRowContext(ctx, getLocationWeatherCacheV2, cacheKey)
	var i WeatherCacheV2
	err := row.Scan(
		&i.CacheKey,
		&i.LocationKey,
		&i.RequestType,
		&i.PayloadJson,
		&i.Source,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMarketCache = `-- name: GetMarketCache :one
SELECT commodity, state, month, modal_price, fetched_at
FROM market_cache WHERE commodity=? AND state='Maharashtra' AND month=?
ORDER BY fetched_at DESC LIMIT 1
`

type GetMarketCacheParams struct {
	Commodity string `json:"commodity"`
	Month     string `json:"month"`
}

func (q *Queries) GetMarketCache(ctx context.Context, arg GetMarketCacheParams) (MarketCache, error) {
	row := q.db.QueryRowContext(ctx, getMarketCache, arg.Commodity, arg.Month)
	var i MarketCache
	err := row.Scan(
		&i.Commodity,
		&i.State,
		&i.Month,
		&i.ModalPrice,
		&i.FetchedAt,
	)
	return i, err
}

const getPortfolioRiskStats = `-- name: GetPortfolioRiskStats :many
SELECT risk_level, COUNT(*) as n, COALESCE(SUM(forecast_deficit),0) as deficit
FROM risk_assessments GROUP BY risk_level
`

type GetPortfolioRiskStatsRow struct {
	RiskLevel sql.NullString `json:"risk_level"`
	N         int64          `json:"n"`
	Deficit   interface{}    `json:"deficit"`
}

func (q *Queries) GetPortfolioRiskStats(ctx context.Context) ([]GetPortfolioRiskStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPortfolioRiskStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPortfolioRiskStatsRow
	for rows.Next() {
		var i GetPortfolioRiskStatsRow
		if err := rows.Scan(&i.RiskLevel, &i.N, &i.Deficit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRiskAssessment = `-- name: GetRiskAssessment :one
SELECT enterprise_id, risk_score, risk_level, forecast_deficit, debt_service_shortfall,
       stress_month, warning_lead_time_days, drivers_json, assessed_at
FROM risk_assessments WHERE enterprise_id = ?
ORDER BY assessed_at DESC LIMIT 1
`

func (q *Queries) GetRiskAssessment(ctx context.Context, enterpriseID string) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, getRiskAssessment, enterpriseID)
	var i RiskAssessment
	err := row.Scan(
		&i.EnterpriseID,
		&i.RiskScore,
		&i.RiskLevel,
		&i.ForecastDeficit,
		&i.DebtServiceShortfall,
		&i.StressMonth,
		&i.WarningLeadTimeDays,
		&i.DriversJson,
		&i.AssessedAt,
	)
	return i, err
}

const getSubmittedRecords = `-- name: GetSubmittedRecords :many
SELECT month, operating_inflow, operating_outflow, savings, loan_repayment, inventory_cost
FROM financial_records WHERE enterprise_id = ? ORDER BY month ASC
`

type GetSubmittedRecordsRow struct {
	Month            string          `json:"month"`
	OperatingInflow  sql.NullFloat64 `json:"operating_inflow"`
	OperatingOutflow sql.NullFloat64 `json:"operating_outflow"`
	Savings          sql.NullFloat64 `json:"savings"`
	LoanRepayment    sql.NullFloat64 `json:"loan_repayment"`
	InventoryCost    sql.NullFloat64 `json:"inventory_cost"`
}

func (q *Queries) GetSubmittedRecords(ctx context.Context, enterpriseID string) ([]GetSubmittedRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubmittedRecords, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmittedRecordsRow
	for rows.Next() {
		var i GetSubmittedRecordsRow
		if err := rows.Scan(
			&i.Month,
			&i.OperatingInflow,
			&i.OperatingOutflow,
			&i.Savings,
			&i.LoanRepayment,
			&i.InventoryCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeline = `-- name: GetTimeline :many
SELECT id, enterprise_id, date, title, description
FROM timeline_events WHERE enterprise_id = ? ORDER BY date DESC LIMIT 50
`

func (q *Queries) GetTimeline(ctx context.Context, enterpriseID string) ([]TimelineEvent, error) {
	rows, err := q.db.QueryContext(ctx, getTimeline, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimelineEvent
	for rows.Next() {
		var i TimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Date,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeatherCache = `-- name: GetWeatherCache :one
SELECT district, rainfall_anomaly, temperature_mean, climate_risk_score, fetched_at
FROM weather_cache WHERE district=?
ORDER BY fetched_at DESC LIMIT 1
`

type GetWeatherCacheRow struct {
	District         sql.NullString  `json:"district"`
	RainfallAnomaly  sql.NullFloat64 `json:"rainfall_anomaly"`
	TemperatureMean  sql.NullFloat64 `json:"temperature_mean"`
	ClimateRiskScore sql.NullFloat64 `json:"climate_risk_score"`
	FetchedAt        sql.NullString  `json:"fetched_at"`
}

func (q *Queries) GetWeatherCache(ctx context.Context, district sql.NullString) (GetWeatherCacheRow, error) {
	row := q.db.QueryRowContext(ctx, getWeatherCache, district)
	var i GetWeatherCacheRow
	err := row.Scan(
		&i.District,
		&i.RainfallAnomaly,
		&i.TemperatureMean,
		&i.ClimateRiskScore,
		&i.FetchedAt,
	)
	return i, err
}

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (id, enterprise_id, risk_level, title, description, created_at, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAlertParams struct {
	ID           string         `json:"id"`
	EnterpriseID string         `json:"enterprise_id"`
	RiskLevel    sql.NullString `json:"risk_level"`
	Title        sql.NullString `json:"title"`
	Description  sql.NullString `json:"description"`
	CreatedAt    sql.NullString `json:"created_at"`
	Status       sql.NullString `json:"status"`
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.ExecContext(ctx, insertAlert,
		arg.ID,
		arg.EnterpriseID,
		arg.RiskLevel,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
		arg.Status,
	)
	return err
}

const insertFinancialRecord = `-- name: InsertFinancialRecord :exec
INSERT OR REPLACE INTO financial_records
 (id, enterprise_id, month, operating_inflow, operating_outflow,
  savings, loan_repayment, inventory_cost, recorded_at, sync_status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'synced')
`

type InsertFinancialRecordParams struct {
	ID               string          `json:"id"`
	EnterpriseID     string          `json:"enterprise_id"`
	Month            string          `json:"month"`
	OperatingInflow  sql.NullFloat64 `json:"operating_inflow"`
	OperatingOutflow sql.NullFloat64 `json:"operating_outflow"`
	Savings          sql.NullFloat64 `json:"savings"`
	LoanRepayment    sql.NullFloat64 `json:"loan_repayment"`
	InventoryCost    sql.NullFloat64 `json:"inventory_cost"`
	RecordedAt       string          `json:"recorded_at"`
}

func (q *Queries) InsertFinancialRecord(ctx context.Context, arg InsertFinancialRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertFinancialRecord,
		arg.ID,
		arg.EnterpriseID,
		arg.Month,
		arg.OperatingInflow,
		arg.OperatingOutflow,
		arg.Savings,
		arg.LoanRepayment,
		arg.InventoryCost,
		arg.RecordedAt,
	)
	return err
}

const insertIntervention = `-- name: InsertIntervention :exec
INSERT INTO interventions (id, enterprise_id, recommended_intervention, illustrative_amount,
  assigned_officer, visit_date, follow_up_date, notes, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInterventionParams struct {
	ID                      string          `json:"id"`
	EnterpriseID            string          `json:"enterprise_id"`
	RecommendedIntervention sql.NullString  `json:"recommended_intervention"`
	IllustrativeAmount      sql.NullFloat64 `json:"illustrative_amount"`
	AssignedOfficer         sql.NullString  `json:"assigned_officer"`
	VisitDate               sql.NullString  `json:"visit_date"`
	FollowUpDate            sql.NullString  `json:"follow_up_date"`
	Notes                   sql.NullString  `json:"notes"`
	Status                  sql.NullString  `json:"status"`
	CreatedAt               sql.NullString  `json:"created_at"`
	UpdatedAt               sql.NullString  `json:"updated_at"`
}

func (q *Queries) InsertIntervention(ctx context.Context, arg InsertInterventionParams) error {
	_, err := q.db.ExecContext(ctx, insertIntervention,
		arg.ID,
		arg.EnterpriseID,
		arg.RecommendedIntervention,
		arg.IllustrativeAmount,
		arg.AssignedOfficer,
		arg.VisitDate,
		arg.FollowUpDate,
		arg.Notes,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTimelineEvent = `-- name: InsertTimelineEvent :exec
INSERT INTO timeline_events (id, enterprise_id, date, title, description) VALUES (?, ?, ?, ?, ?)
`

type InsertTimelineEventParams struct {
	ID           string         `json:"id"`
	EnterpriseID string         `json:"enterprise_id"`
	Date         string         `json:"date"`
	Title        sql.NullString `json:"title"`
	Description  sql.NullString `json:"description"`
}

func (q *Queries) InsertTimelineEvent(ctx context.Context, arg InsertTimelineEventParams) error {
	_, err := q.db.ExecContext(ctx, insertTimelineEvent,
		arg.ID,
		arg.EnterpriseID,
		arg.Date,
		arg.Title,
		arg.Description,
	)
	return err
}

const listInterventionsByEnterprise = `-- name: ListInterventionsByEnterprise :many
SELECT id, enterprise_id, recommended_intervention, illustrative_amount,
       assigned_officer, visit_date, follow_up_date, notes, status, created_at, updated_at
FROM interventions WHERE enterprise_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListInterventionsByEnterprise(ctx context.Context, enterpriseID string) ([]Intervention, error) {
	rows, err := q.db.QueryContext(ctx, listInterventionsByEnterprise, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Intervention
	for rows.Next() {
		var i Intervention
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.RecommendedIntervention,
			&i.IllustrativeAmount,
			&i.AssignedOfficer,
			&i.VisitDate,
			&i.FollowUpDate,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentInterventions = `-- name: ListRecentInterventions :many
SELECT id, enterprise_id, recommended_intervention, illustrative_amount,
       assigned_officer, visit_date, follow_up_date, notes, status, created_at, updated_at
FROM interventions ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListRecentInterventions(ctx context.Context) ([]Intervention, error) {
	rows, err := q.db.QueryContext(ctx, listRecentInterventions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Intervention
	for rows.Next() {
		var i Intervention
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.RecommendedIntervention,
			&i.IllustrativeAmount,
			&i.AssignedOfficer,
			&i.VisitDate,
			&i.FollowUpDate,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterventionStatus = `-- name: UpdateInterventionStatus :exec
UPDATE interventions SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateInterventionStatusParams struct {
	Status    sql.NullString `json:"status"`
	UpdatedAt sql.NullString `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateInterventionStatus(ctx context.Context, arg UpdateInterventionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInterventionStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const upsertAgmarknetFilter = `-- name: UpsertAgmarknetFilter :exec
INSERT OR REPLACE INTO agmarknet_filters (filter_type, filter_id, filter_name, fetched_at)
VALUES (?, ?, ?, ?)
`

type UpsertAgmarknetFilterParams struct {
	FilterType string    `json:"filter_type"`
	FilterID   string    `json:"filter_id"`
	FilterName string    `json:"filter_name"`
	FetchedAt  time.Time `json:"fetched_at"`
}

func (q *Queries) UpsertAgmarknetFilter(ctx context.Context, arg UpsertAgmarknetFilterParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgmarknetFilter,
		arg.FilterType,
		arg.FilterID,
		arg.FilterName,
		arg.FetchedAt,
	)
	return err
}

const upsertAgmarknetPrice = `-- name: UpsertAgmarknetPrice :exec
INSERT OR REPLACE INTO agmarknet_daily_prices 
 (id, arrival_date, state_id, state_name, district_id, district_name, market_id, market_name, 
  commodity_id, commodity_name, variety_id, variety_name, grade_id, grade_name, 
  min_price, max_price, modal_price, arrivals, price_unit, arrival_unit, source, fetched_at, raw_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertAgmarknetPriceParams struct {
	ID            string          `json:"id"`
	ArrivalDate   time.Time       `json:"arrival_date"`
	StateID       sql.NullString  `json:"state_id"`
	StateName     sql.NullString  `json:"state_name"`
	DistrictID    sql.NullString  `json:"district_id"`
	DistrictName  sql.NullString  `json:"district_name"`
	MarketID      sql.NullString  `json:"market_id"`
	MarketName    sql.NullString  `json:"market_name"`
	CommodityID   sql.NullString  `json:"commodity_id"`
	CommodityName sql.NullString  `json:"commodity_name"`
	VarietyID     sql.NullString  `json:"variety_id"`
	VarietyName   sql.NullString  `json:"variety_name"`
	GradeID       sql.NullString  `json:"grade_id"`
	GradeName     sql.NullString  `json:"grade_name"`
	MinPrice      sql.NullFloat64 `json:"min_price"`
	MaxPrice      sql.NullFloat64 `json:"max_price"`
	ModalPrice    sql.NullFloat64 `json:"modal_price"`
	Arrivals      sql.NullFloat64 `json:"arrivals"`
	PriceUnit     sql.NullString  `json:"price_unit"`
	ArrivalUnit   sql.NullString  `json:"arrival_unit"`
	Source        string          `json:"source"`
	FetchedAt     time.Time       `json:"fetched_at"`
	RawHash       string          `json:"raw_hash"`
}

func (q *Queries) UpsertAgmarknetPrice(ctx context.Context, arg UpsertAgmarknetPriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgmarknetPrice,
		arg.ID,
		arg.ArrivalDate,
		arg.StateID,
		arg.StateName,
		arg.DistrictID,
		arg.DistrictName,
		arg.MarketID,
		arg.MarketName,
		arg.CommodityID,
		arg.CommodityName,
		arg.VarietyID,
		arg.VarietyName,
		arg.GradeID,
		arg.GradeName,
		arg.MinPrice,
		arg.MaxPrice,
		arg.ModalPrice,
		arg.Arrivals,
		arg.PriceUnit,
		arg.ArrivalUnit,
		arg.Source,
		arg.FetchedAt,
		arg.RawHash,
	)
	return err
}

const upsertForecastCache = `-- name: UpsertForecastCache :exec
INSERT OR REPLACE INTO forecast_cache (enterprise_id, record_hash, model_version, forecast_json, generated_at)
VALUES (?, ?, ?, ?, ?)
`

type UpsertForecastCacheParams struct {
	EnterpriseID string         `json:"enterprise_id"`
	RecordHash   string         `json:"record_hash"`
	ModelVersion sql.NullString `json:"model_version"`
	ForecastJson sql.NullString `json:"forecast_json"`
	GeneratedAt  sql.NullString `json:"generated_at"`
}

func (q *Queries) UpsertForecastCache(ctx context.Context, arg UpsertForecastCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertForecastCache,
		arg.EnterpriseID,
		arg.RecordHash,
		arg.ModelVersion,
		arg.ForecastJson,
		arg.GeneratedAt,
	)
	return err
}

const upsertLocationWeatherCacheV2 = `-- name: UpsertLocationWeatherCacheV2 :exec
INSERT OR REPLACE INTO weather_cache_v2 
 (cache_key, location_key, request_type, payload_json, source, fetched_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type UpsertLocationWeatherCacheV2Params struct {
	CacheKey    string `json:"cache_key"`
	LocationKey string `json:"location_key"`
	RequestType string `json:"request_type"`
	PayloadJson string `json:"payload_json"`
	Source      string `json:"source"`
	FetchedAt   string `json:"fetched_at"`
	ExpiresAt   string `json:"expires_at"`
}

func (q *Queries) UpsertLocationWeatherCacheV2(ctx context.Context, arg UpsertLocationWeatherCacheV2Params) error {
	_, err := q.db.ExecContext(ctx, upsertLocationWeatherCacheV2,
		arg.CacheKey,
		arg.LocationKey,
		arg.RequestType,
		arg.PayloadJson,
		arg.Source,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}

const upsertMarketCache = `-- name: UpsertMarketCache :exec
INSERT OR REPLACE INTO market_cache (commodity, state, month, modal_price, fetched_at)
VALUES (?, 'Maharashtra', ?, ?, ?)
`

type UpsertMarketCacheParams struct {
	Commodity  string          `json:"commodity"`
	Month      string          `json:"month"`
	ModalPrice sql.NullFloat64 `json:"modal_price"`
	FetchedAt  sql.NullString  `json:"fetched_at"`
}

func (q *Queries) UpsertMarketCache(ctx context.Context, arg UpsertMarketCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketCache,
		arg.Commodity,
		arg.Month,
		arg.ModalPrice,
		arg.FetchedAt,
	)
	return err
}

const upsertRiskAssessment = `-- name: UpsertRiskAssessment :exec
INSERT OR REPLACE INTO risk_assessments
 (enterprise_id, risk_score, risk_level, forecast_deficit, debt_service_shortfall,
  stress_month, warning_lead_time_days, drivers_json, assessed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertRiskAssessmentParams struct {
	EnterpriseID         string          `json:"enterprise_id"`
	RiskScore            sql.NullInt64   `json:"risk_score"`
	RiskLevel            sql.NullString  `json:"risk_level"`
	ForecastDeficit      sql.NullFloat64 `json:"forecast_deficit"`
	DebtServiceShortfall sql.NullFloat64 `json:"debt_service_shortfall"`
	StressMonth          sql.NullString  `json:"stress_month"`
	WarningLeadTimeDays  sql.NullInt64   `json:"warning_lead_time_days"`
	DriversJson          sql.NullString  `json:"drivers_json"`
	AssessedAt           sql.NullString  `json:"assessed_at"`
}

func (q *Queries) UpsertRiskAssessment(ctx context.Context, arg UpsertRiskAssessmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertRiskAssessment,
		arg.EnterpriseID,
		arg.RiskScore,
		arg.RiskLevel,
		arg.ForecastDeficit,
		arg.DebtServiceShortfall,
		arg.StressMonth,
		arg.WarningLeadTimeDays,
		arg.DriversJson,
		arg.AssessedAt,
	)
	return err
}

const upsertWeatherCache = `-- name: UpsertWeatherCache :exec
INSERT OR REPLACE INTO weather_cache (district, rainfall_anomaly, temperature_mean, climate_risk_score, fetched_at)
VALUES (?, ?, ?, ?, ?)
`

type UpsertWeatherCacheParams struct {
	District         sql.NullString  `json:"district"`
	RainfallAnomaly  sql.NullFloat64 `json:"rainfall_anomaly"`
	TemperatureMean  sql.NullFloat64 `json:"temperature_mean"`
	ClimateRiskScore sql.NullFloat64 `json:"climate_risk_score"`
	FetchedAt        sql.NullString  `json:"fetched_at"`
}

func (q *Queries) UpsertWeatherCache(ctx context.Context, arg UpsertWeatherCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeatherCache,
		arg.District,
		arg.RainfallAnomaly,
		arg.TemperatureMean,
		arg.ClimateRiskScore,
		arg.FetchedAt,
	)
	return err
}
