// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/assessment.proto

package assessmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	PartnerId     string                 `protobuf:"bytes,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	UserRefHash   string                 `protobuf:"bytes,3,opt,name=user_ref_hash,json=userRefHash,proto3" json:"user_ref_hash,omitempty"`
	Products      []string               `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	ConsentId     string                 `protobuf:"bytes,5,opt,name=consent_id,json=consentId,proto3" json:"consent_id,omitempty"`
	PartnerRefId  string                 `protobuf:"bytes,6,opt,name=partner_ref_id,json=partnerRefId,proto3" json:"partner_ref_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentRequest) Reset() {
	*x = AssessmentRequest{}
	mi := &file_proto_assessment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentRequest) ProtoMessage() {}

func (x *AssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentRequest.ProtoReflect.Descriptor instead.
func (*AssessmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{0}
}

func (x *AssessmentRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *AssessmentRequest) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *AssessmentRequest) GetUserRefHash() string {
	if x != nil {
		return x.UserRefHash
	}
	return ""
}

func (x *AssessmentRequest) GetProducts() []string {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *AssessmentRequest) GetConsentId() string {
	if x != nil {
		return x.ConsentId
	}
	return ""
}

func (x *AssessmentRequest) GetPartnerRefId() string {
	if x != nil {
		return x.PartnerRefId
	}
	return ""
}

type AssessmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentStatusRequest) Reset() {
	*x = AssessmentStatusRequest{}
	mi := &file_proto_assessment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentStatusRequest) ProtoMessage() {}

func (x *AssessmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentStatusRequest.ProtoReflect.Descriptor instead.
func (*AssessmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{1}
}

func (x *AssessmentStatusRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

type AssessmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OverallSignal string                 `protobuf:"bytes,3,opt,name=overall_signal,json=overallSignal,proto3" json:"overall_signal,omitempty"`
	ScoreVersion  string                 `protobuf:"bytes,4,opt,name=score_version,json=scoreVersion,proto3" json:"score_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentStatusResponse) Reset() {
	*x = AssessmentStatusResponse{}
	mi := &file_proto_assessment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentStatusResponse) ProtoMessage() {}

func (x *AssessmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentStatusResponse.ProtoReflect.Descriptor instead.
func (*AssessmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{2}
}

func (x *AssessmentStatusResponse) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *AssessmentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssessmentStatusResponse) GetOverallSignal() string {
	if x != nil {
		return x.OverallSignal
	}
	return ""
}

func (x *AssessmentStatusResponse) GetScoreVersion() string {
	if x != nil {
		return x.ScoreVersion
	}
	return ""
}

var File_proto_assessment_proto protoreflect.FileDescriptor

const file_proto_assessment_proto_rawDesc = "" +
	"\n" +
	"\x16proto/assessment.proto\x12\x13zeyro.assessment.v1\"\xdc\x01\n" +
	"\x11AssessmentRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12\x1d\n" +
	"\n" +
	"partner_id\x18\x02 \x01(\tR\tpartnerId\x12\"\n" +
	"\ruser_ref_hash\x18\x03 \x01(\tR\vuserRefHash\x12\x1a\n" +
	"\bproducts\x18\x04 \x03(\tR\bproducts\x12\x1d\n" +
	"\n" +
	"consent_id\x18\x05 \x01(\tR\tconsentId\x12$\n" +
	"\x0epartner_ref_id\x18\x06 \x01(\tR\fpartnerRefId\">\n" +
	"\x17AssessmentStatusRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\"\xa3\x01\n" +
	"\x18AssessmentStatusResponse\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0eoverall_signal\x18\x03 \x01(\tR\roverallSignal\x12#\n" +
	"\rscore_version\x18\x04 \x01(\tR\fscoreVersion2\xf2\x01\n" +
	"\x11AssessmentService\x12i\n" +
	"\x10CreateAssessment\x12&.zeyro.assessment.v1.AssessmentRequest\x1a-.zeyro.assessment.v1.AssessmentStatusResponse\x12r\n" +
	"\x13GetAssessmentStatus\x12,.zeyro.assessment.v1.AssessmentStatusRequest\x1a-.zeyro.assessment.v1.AssessmentStatusResponseB?Z=github.com/arthazeyro/zeyro-b2b/proto/assessment;assessmentpbb\x06proto3"

var (
	file_proto_assessment_proto_rawDescOnce sync.Once
	file_proto_assessment_proto_rawDescData []byte
)

func file_proto_assessment_proto_rawDescGZIP() []byte {
	file_proto_assessment_proto_rawDescOnce.Do(func() {
		file_proto_assessment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_assessment_proto_rawDesc), len(file_proto_assessment_proto_rawDesc)))
	})
	return file_proto_assessment_proto_rawDescData
}

var file_proto_assessment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_assessment_proto_goTypes = []any{
	(*AssessmentRequest)(nil),        // 0: zeyro.assessment.v1.AssessmentRequest
	(*AssessmentStatusRequest)(nil),  // 1: zeyro.assessment.v1.AssessmentStatusRequest
	(*AssessmentStatusResponse)(nil), // 2: zeyro.assessment.v1.AssessmentStatusResponse
}
var file_proto_assessment_proto_depIdxs = []int32{
	0, // 0: zeyro.assessment.v1.AssessmentService.CreateAssessment:input_type -> zeyro.assessment.v1.AssessmentRequest
	1, // 1: zeyro.assessment.v1.AssessmentService.GetAssessmentStatus:input_type -> zeyro.assessment.v1.AssessmentStatusRequest
	2, // 2: zeyro.assessment.v1.AssessmentService.CreateAssessment:output_type -> zeyro.assessment.v1.AssessmentStatusResponse
	2, // 3: zeyro.assessment.v1.AssessmentService.GetAssessmentStatus:output_type -> zeyro.assessment.v1.AssessmentStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_assessment_proto_init() }
func file_proto_assessment_proto_init() {
	if File_proto_assessment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_assessment_proto_rawDesc), len(file_proto_assessment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_assessment_proto_goTypes,
		DependencyIndexes: file_proto_assessment_proto_depIdxs,
		MessageInfos:      file_proto_assessment_proto_msgTypes,
	}.Build()
	File_proto_assessment_proto = out.File
	file_proto_assessment_proto_goTypes = nil
	file_proto_assessment_proto_depIdxs = nil
}
