// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/assessment.proto

package assessmentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssessmentService_CreateAssessment_FullMethodName    = "/zeyro.assessment.v1.AssessmentService/CreateAssessment"
	AssessmentService_GetAssessmentStatus_FullMethodName = "/zeyro.assessment.v1.AssessmentService/GetAssessmentStatus"
)

// AssessmentServiceClient is the client API for AssessmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssessmentServiceClient interface {
	CreateAssessment(ctx context.Context, in *AssessmentRequest, opts ...grpc.CallOption) (*AssessmentStatusResponse, error)
	GetAssessmentStatus(ctx context.Context, in *AssessmentStatusRequest, opts ...grpc.CallOption) (*AssessmentStatusResponse, error)
}

type assessmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssessmentServiceClient(cc grpc.ClientConnInterface) AssessmentServiceClient {
	return &assessmentServiceClient{cc}
}

func (c *assessmentServiceClient) CreateAssessment(ctx context.Context, in *AssessmentRequest, opts ...grpc.CallOption) (*AssessmentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssessmentStatusResponse)
	err := c.cc.Invoke(ctx, AssessmentService_CreateAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetAssessmentStatus(ctx context.Context, in *AssessmentStatusRequest, opts ...grpc.CallOption) (*AssessmentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssessmentStatusResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GetAssessmentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssessmentServiceServer is the server API for AssessmentService service.
// All implementations must embed UnimplementedAssessmentServiceServer
// for forward compatibility.
type AssessmentServiceServer interface {
	CreateAssessment(context.Context, *AssessmentRequest) (*AssessmentStatusResponse, error)
	GetAssessmentStatus(context.Context, *AssessmentStatusRequest) (*AssessmentStatusResponse, error)
	mustEmbedUnimplementedAssessmentServiceServer()
}

// UnimplementedAssessmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssessmentServiceServer struct{}

func (UnimplementedAssessmentServiceServer) CreateAssessment(context.Context, *AssessmentRequest) (*AssessmentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAssessment not implemented")
}
func (UnimplementedAssessmentServiceServer) GetAssessmentStatus(context.Context, *AssessmentStatusRequest) (*AssessmentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssessmentStatus not implemented")
}
func (UnimplementedAssessmentServiceServer) mustEmbedUnimplementedAssessmentServiceServer() {}
func (UnimplementedAssessmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeAssessmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssessmentServiceServer will
// result in compilation errors.
type UnsafeAssessmentServiceServer interface {
	mustEmbedUnimplementedAssessmentServiceServer()
}

func RegisterAssessmentServiceServer(s grpc.ServiceRegistrar, srv AssessmentServiceServer) {
	// If the following call panics, it indicates UnimplementedAssessmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssessmentService_ServiceDesc, srv)
}

func _AssessmentService_CreateAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).CreateAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_CreateAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).CreateAssessment(ctx, req.(*AssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetAssessmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetAssessmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetAssessmentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetAssessmentStatus(ctx, req.(*AssessmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssessmentService_ServiceDesc is the grpc.ServiceDesc for AssessmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssessmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zeyro.assessment.v1.AssessmentService",
	HandlerType: (*AssessmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssessment",
			Handler:    _AssessmentService_CreateAssessment_Handler,
		},
		{
			MethodName: "GetAssessmentStatus",
			Handler:    _AssessmentService_GetAssessmentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/assessment.proto",
}
