// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/features.proto

package featurespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeatureService_RecomputeFeatures_FullMethodName = "/zeyro.features.v1.FeatureService/RecomputeFeatures"
	FeatureService_GetFeatures_FullMethodName       = "/zeyro.features.v1.FeatureService/GetFeatures"
)

// FeatureServiceClient is the client API for FeatureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeatureServiceClient interface {
	RecomputeFeatures(ctx context.Context, in *FeatureRecomputeRequest, opts ...grpc.CallOption) (*FeatureResponse, error)
	GetFeatures(ctx context.Context, in *FeatureRecomputeRequest, opts ...grpc.CallOption) (*FeatureResponse, error)
}

type featureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureServiceClient(cc grpc.ClientConnInterface) FeatureServiceClient {
	return &featureServiceClient{cc}
}

func (c *featureServiceClient) RecomputeFeatures(ctx context.Context, in *FeatureRecomputeRequest, opts ...grpc.CallOption) (*FeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureResponse)
	err := c.cc.Invoke(ctx, FeatureService_RecomputeFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) GetFeatures(ctx context.Context, in *FeatureRecomputeRequest, opts ...grpc.CallOption) (*FeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureResponse)
	err := c.cc.Invoke(ctx, FeatureService_GetFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeatureServiceServer is the server API for FeatureService service.
// All implementations must embed UnimplementedFeatureServiceServer
// for forward compatibility.
type FeatureServiceServer interface {
	RecomputeFeatures(context.Context, *FeatureRecomputeRequest) (*FeatureResponse, error)
	GetFeatures(context.Context, *FeatureRecomputeRequest) (*FeatureResponse, error)
	mustEmbedUnimplementedFeatureServiceServer()
}

// UnimplementedFeatureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeatureServiceServer struct{}

func (UnimplementedFeatureServiceServer) RecomputeFeatures(context.Context, *FeatureRecomputeRequest) (*FeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecomputeFeatures not implemented")
}
func (UnimplementedFeatureServiceServer) GetFeatures(context.Context, *FeatureRecomputeRequest) (*FeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeatures not implemented")
}
func (UnimplementedFeatureServiceServer) mustEmbedUnimplementedFeatureServiceServer() {}
func (UnimplementedFeatureServiceServer) testEmbeddedByValue()                        {}

// UnsafeFeatureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureServiceServer will
// result in compilation errors.
type UnsafeFeatureServiceServer interface {
	mustEmbedUnimplementedFeatureServiceServer()
}

func RegisterFeatureServiceServer(s grpc.ServiceRegistrar, srv FeatureServiceServer) {
	// If the following call panics, it indicates UnimplementedFeatureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeatureService_ServiceDesc, srv)
}

func _FeatureService_RecomputeFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureRecomputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).RecomputeFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_RecomputeFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).RecomputeFeatures(ctx, req.(*FeatureRecomputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_GetFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureRecomputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).GetFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureService_GetFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).GetFeatures(ctx, req.(*FeatureRecomputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeatureService_ServiceDesc is the grpc.ServiceDesc for FeatureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zeyro.features.v1.FeatureService",
	HandlerType: (*FeatureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecomputeFeatures",
			Handler:    _FeatureService_RecomputeFeatures_Handler,
		},
		{
			MethodName: "GetFeatures",
			Handler:    _FeatureService_GetFeatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/features.proto",
}
