// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/features.proto

package featurespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureRecomputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRefHash   string                 `protobuf:"bytes,1,opt,name=user_ref_hash,json=userRefHash,proto3" json:"user_ref_hash,omitempty"`
	Window        string                 `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	FeatureGroups []string               `protobuf:"bytes,3,rep,name=feature_groups,json=featureGroups,proto3" json:"feature_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureRecomputeRequest) Reset() {
	*x = FeatureRecomputeRequest{}
	mi := &file_proto_features_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureRecomputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureRecomputeRequest) ProtoMessage() {}

func (x *FeatureRecomputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_features_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureRecomputeRequest.ProtoReflect.Descriptor instead.
func (*FeatureRecomputeRequest) Descriptor() ([]byte, []int) {
	return file_proto_features_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureRecomputeRequest) GetUserRefHash() string {
	if x != nil {
		return x.UserRefHash
	}
	return ""
}

func (x *FeatureRecomputeRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *FeatureRecomputeRequest) GetFeatureGroups() []string {
	if x != nil {
		return x.FeatureGroups
	}
	return nil
}

type FeatureRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FeatureGroup     string                 `protobuf:"bytes,1,opt,name=feature_group,json=featureGroup,proto3" json:"feature_group,omitempty"`
	FeatureName      string                 `protobuf:"bytes,2,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	FeatureValueJson string                 `protobuf:"bytes,3,opt,name=feature_value_json,json=featureValueJson,proto3" json:"feature_value_json,omitempty"`
	ComputedAt       string                 `protobuf:"bytes,4,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeatureRecord) Reset() {
	*x = FeatureRecord{}
	mi := &file_proto_features_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureRecord) ProtoMessage() {}

func (x *FeatureRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_features_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureRecord.ProtoReflect.Descriptor instead.
func (*FeatureRecord) Descriptor() ([]byte, []int) {
	return file_proto_features_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureRecord) GetFeatureGroup() string {
	if x != nil {
		return x.FeatureGroup
	}
	return ""
}

func (x *FeatureRecord) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *FeatureRecord) GetFeatureValueJson() string {
	if x != nil {
		return x.FeatureValueJson
	}
	return ""
}

func (x *FeatureRecord) GetComputedAt() string {
	if x != nil {
		return x.ComputedAt
	}
	return ""
}

type FeatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRefHash   string                 `protobuf:"bytes,1,opt,name=user_ref_hash,json=userRefHash,proto3" json:"user_ref_hash,omitempty"`
	Window        string                 `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	Records       []*FeatureRecord       `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureResponse) Reset() {
	*x = FeatureResponse{}
	mi := &file_proto_features_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureResponse) ProtoMessage() {}

func (x *FeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_features_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureResponse.ProtoReflect.Descriptor instead.
func (*FeatureResponse) Descriptor() ([]byte, []int) {
	return file_proto_features_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureResponse) GetUserRefHash() string {
	if x != nil {
		return x.UserRefHash
	}
	return ""
}

func (x *FeatureResponse) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *FeatureResponse) GetRecords() []*FeatureRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_proto_features_proto protoreflect.FileDescriptor

const file_proto_features_proto_rawDesc = "" +
	"\n" +
	"\x14proto/features.proto\x12\x11zeyro.features.v1\"|\n" +
	"\x17FeatureRecomputeRequest\x12\"\n" +
	"\ruser_ref_hash\x18\x01 \x01(\tR\vuserRefHash\x12\x16\n" +
	"\x06window\x18\x02 \x01(\tR\x06window\x12%\n" +
	"\x0efeature_groups\x18\x03 \x03(\tR\rfeatureGroups\"\xa6\x01\n" +
	"\rFeatureRecord\x12#\n" +
	"\rfeature_group\x18\x01 \x01(\tR\ffeatureGroup\x12!\n" +
	"\ffeature_name\x18\x02 \x01(\tR\vfeatureName\x12,\n" +
	"\x12feature_value_json\x18\x03 \x01(\tR\x10featureValueJson\x12\x1f\n" +
	"\vcomputed_at\x18\x04 \x01(\tR\n" +
	"computedAt\"\x89\x01\n" +
	"\x0fFeatureResponse\x12\"\n" +
	"\ruser_ref_hash\x18\x01 \x01(\tR\vuserRefHash\x12\x16\n" +
	"\x06window\x18\x02 \x01(\tR\x06window\x12:\n" +
	"\arecords\x18\x03 \x03(\v2 .zeyro.features.v1.FeatureRecordR\arecords2\xd4\x01\n" +
	"\x0eFeatureService\x12c\n" +
	"\x11RecomputeFeatures\x12*.zeyro.features.v1.FeatureRecomputeRequest\x1a\".zeyro.features.v1.FeatureResponse\x12]\n" +
	"\vGetFeatures\x12*.zeyro.features.v1.FeatureRecomputeRequest\x1a\".zeyro.features.v1.FeatureResponseB;Z9github.com/arthazeyro/zeyro-b2b/proto/features;featurespbb\x06proto3"

var (
	file_proto_features_proto_rawDescOnce sync.Once
	file_proto_features_proto_rawDescData []byte
)

func file_proto_features_proto_rawDescGZIP() []byte {
	file_proto_features_proto_rawDescOnce.Do(func() {
		file_proto_features_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_features_proto_rawDesc), len(file_proto_features_proto_rawDesc)))
	})
	return file_proto_features_proto_rawDescData
}

var file_proto_features_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_features_proto_goTypes = []any{
	(*FeatureRecomputeRequest)(nil), // 0: zeyro.features.v1.FeatureRecomputeRequest
	(*FeatureRecord)(nil),           // 1: zeyro.features.v1.FeatureRecord
	(*FeatureResponse)(nil),         // 2: zeyro.features.v1.FeatureResponse
}
var file_proto_features_proto_depIdxs = []int32{
	1, // 0: zeyro.features.v1.FeatureResponse.records:type_name -> zeyro.features.v1.FeatureRecord
	0, // 1: zeyro.features.v1.FeatureService.RecomputeFeatures:input_type -> zeyro.features.v1.FeatureRecomputeRequest
	0, // 2: zeyro.features.v1.FeatureService.GetFeatures:input_type -> zeyro.features.v1.FeatureRecomputeRequest
	2, // 3: zeyro.features.v1.FeatureService.RecomputeFeatures:output_type -> zeyro.features.v1.FeatureResponse
	2, // 4: zeyro.features.v1.FeatureService.GetFeatures:output_type -> zeyro.features.v1.FeatureResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_features_proto_init() }
func file_proto_features_proto_init() {
	if File_proto_features_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_features_proto_rawDesc), len(file_proto_features_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_features_proto_goTypes,
		DependencyIndexes: file_proto_features_proto_depIdxs,
		MessageInfos:      file_proto_features_proto_msgTypes,
	}.Build()
	File_proto_features_proto = out.File
	file_proto_features_proto_goTypes = nil
	file_proto_features_proto_depIdxs = nil
}
